GET http://localhost:18080/people

###

POST http://localhost:18080/people/11 
content-type: application/json

{
	"Firstname" : "aaa",
	"Lastname" : "bbb",
	"Address" : {
		"City" : "xxx",
		"State" : "yyy"
	}
}

###

DELETE http://localhost:18080/people/11

