issues:
  exclude:
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    - func name will be used as test\.Test.* by other packages, and that stutters; consider calling this
    - (possible misuse of unsafe.Pointer|should have signature)
    - Use of unsafe calls should be audited
    - Subprocess launch(ed with variable|ing should be audited)
    - G104
    - (Expect directory permissions to be 0750 or less|Expect file permissions to be 0600 or less)
    - Potential file inclusion via variable
  exclude-rules:
    - linters:
        - forcetypeassert
      path: _test\.go
      source: args\.Get\(\d\)
    - linters:
        - gomoddirectives
      text: replacement are not allowed
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  disable-all: true
  enable:
    - bidichk
    - depguard
    - dogsled
    - dupword
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - gofumpt
    - goimports
    - gomnd
    - gomoddirectives
    - ineffassign
    - interfacebloat
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - tagalign
    - testableexamples
    - testpackage
    - usestdlibvars
    - wsl
linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: github.com/ExpansiveWorlds/instrumentedsql
            desc: Unmaintained, and performs poorly. Use github.com/luna-duclos/instrumentedsql
          - pkg: github.com/gogo/protobuf
            desc: Incompatible with github.com/golang/protobuf generated code in subtle ways that fail silently at runtime
          - pkg: github.com/kr/pretty
            desc: Performs poorly, do not use
          - pkg: github.com/kr/text
            desc: Performs poorly, do not use
  errcheck:
    check-blank: true
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(CURRENT_MODULE) 
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - performance
      - style
  gocyclo:
    min-complexity: 10
  gomnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
  govet:
    check-shadowing: true
  nakedret:
    max-func-lines: 0
  nestif:
    min-complexity: 2
  nolintlint:
    require-explanation: true
    require-specific: true
output:
  sort-results: true
  unique-by-line: false
run:
  skip-dirs:
    - generated
  skip-files:
    - (.*\.|^)generated.*\.go
  timeout: 10m
